/*
 * Copyright 2014 Robin Stuart
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.org.okapibarcode.gui;

/**
 * Show "About Okapi" information
 *
 * @author <a href="mailto:rstuart114@gmail.com">Robin Stuart</a>
 */
public class AboutOkapi extends javax.swing.JFrame {

    /**
     * Creates new form AboutOkapi
     */
    public AboutOkapi() {
        initComponents();
        titleLabel.setText("<html><b>Okapi Barcode</b><br><br>" + "A free barcode generator<br>" + "&copy; 2006-2016 Robin Stuart &amp; Robert Elliott<br>" + "Licensed under the Apache License, Version 2.0<br><br>" + "&quot;QR Code&quot; is a registerered trademark of Denso Corp.<br>" + "&quot;Telepen&quot; is a registered trademark of SB Electronics.<br></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {
        titleLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Okapi");
        setResizable(false);
        // NOI18N
        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        titleLabel.setText("Okapi Barcode");
        okButton.setText("OK");
        // NOI18N
        okButton.setName("btnOK");
        okButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(336, 336, 336).addComponent(okButton).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(okButton).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pack();
    }

    // </editor-fold>//GEN-END:initComponents
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }

    //GEN-LAST:event_okButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;

    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
