/*
 * Copyright 2014 Robin Stuart
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.org.okapibarcode.gui;

/**
 * @author <a href="mailto:rstuart114@gmail.com">Robin Stuart</a>
 */
public class AddComposite extends javax.swing.JFrame {

    /**
     * Creates new form AddComposite
     */
    public AddComposite() {
        initComponents();
        pullData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {
        compositeLabel = new javax.swing.JLabel();
        compsitePane = new javax.swing.JScrollPane();
        compositeText = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        compositeLabel.setText("Composite Data");
        // NOI18N
        compositeLabel.setName("");
        compositeText.setColumns(20);
        compositeText.setRows(5);
        compsitePane.setViewportView(compositeText);
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(compsitePane, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addComponent(compositeLabel).addGap(0, 0, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(okButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cancelButton))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(compositeLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(compsitePane, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(cancelButton).addComponent(okButton)).addGap(11, 11, 11)));
        pack();
    }

    // </editor-fold>//GEN-END:initComponents
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }

    //GEN-LAST:event_cancelButtonActionPerformed
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        OkapiUI.compositeInputField.setText(compositeText.getText());
        dispose();
    }

    //GEN-LAST:event_okButtonActionPerformed
    private void pullData() {
        compositeText.setText(OkapiUI.compositeInputField.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;

    private javax.swing.JLabel compositeLabel;

    private javax.swing.JTextArea compositeText;

    private javax.swing.JScrollPane compsitePane;

    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
