/*
 * Copyright 2014 Robin Stuart
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.org.okapibarcode.gui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * Allow user to enter larger data, or input from file
 *
 * @author <a href="mailto:rstuart114@gmail.com">Robin Stuart</a>
 */
public class MoreData extends javax.swing.JFrame {

    /**
     * Creates new form MoreData
     */
    public MoreData() {
        initComponents();
        pullData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    void initComponents() {
        dataLabel = new java.awt.Label();
        dataInputArea = new java.awt.TextArea();
        fromFileButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Data");
        setResizable(false);
        // NOI18N
        dataLabel.setName("dataLabel");
        dataLabel.setText("Data");
        // NOI18N
        dataInputArea.setName("dataField");
        fromFileButton.setText("From File...");
        fromFileButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throw new UnsupportedOperationException("STUB: not implemented");
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addComponent(resetButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(fromFileButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(okButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cancelButton)).addComponent(dataInputArea, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(dataInputArea, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(resetButton).addComponent(okButton).addComponent(cancelButton).addComponent(fromFileButton)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pack();
    }

    // </editor-fold>//GEN-END:initComponents
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_resetButtonActionPerformed
        // Clear data area
        dataInputArea.setText("");
    }

    //GEN-LAST:event_resetButtonActionPerformed
    private void fromFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_fromFileButtonActionPerformed
        // Allow user to select a file, and read input data from that file
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                dataInputArea.setText(OpenFile.ReadFile(file, false));
            } catch (Exception e) {
                System.out.println("Cannot read from file" + fileChooser.getSelectedFile().toString());
            }
        }
    }

    //GEN-LAST:event_fromFileButtonActionPerformed
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_cancelButtonActionPerformed
        // Exit dialogue without saving content
        dispose();
    }

    //GEN-LAST:event_cancelButtonActionPerformed
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_okButtonActionPerformed
        // Exit dialogue and send content to main window
        OkapiUI.dataInputField.setText(dataInputArea.getText());
        dispose();
    }

    //GEN-LAST:event_okButtonActionPerformed
    private void pullData() {
        dataInputArea.setText(OkapiUI.dataInputField.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;

    private java.awt.TextArea dataInputArea;

    private java.awt.Label dataLabel;

    private javax.swing.JButton fromFileButton;

    private javax.swing.JButton okButton;

    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
